//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Leagues.League.commandHandler
{
    using CQRSAzure.EventSourcing;
    using CQRSAzure.CommandDefinition;
    using CQRSAzure.CommandHandler;
    using Leagues.League;
    using Leagues.League.commandDefinition;
    
    
    /// <summary>
    /// Create a new running league to which teams can belong
    /// </summary>
    [CQRSAzure.EventSourcing.DomainNameAttribute("Leagues")]
    [CQRSAzure.EventSourcing.Category("Administration")]
    public partial class Create_New_League_Handler : CommandHandlerBase<ICreate_New_League_Definition>, ICreate_New_League_Handler
    {
        
        /// <summary>
        /// Handle the command definition
        /// Create a new running league to which teams can belong
        /// </summary>
        /// <param name="cmdToHandle">
        /// The instance of the command definition to handle
        /// </param>
        public override void HandleCommand(ICreate_New_League_Definition cmdToHandle)
        {
            // TODO : Process the command definition passed in
        }
    }
}
