//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using CQRSAzure.CommandHandler;
using Leagues.League.commandDefinition;

/// <remarks>
/// Each league will have an unique name
/// </remarks>
namespace Leagues.League.commandHandler
{
    
    /// <summary>
    /// Create a new running league to which teams can belong
    /// </summary>
    public  interface ICreate_New_League_Handler : 
        ICommandHandler<ICreate_New_League_Definition>
    {
    }
}
