//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

/// <remarks>
/// Each league will have an unique name
/// </remarks>
namespace Leagues.League.commandHandler
{
    using CQRSAzure.EventSourcing;
    using CQRSAzure.CommandDefinition;
    using CQRSAzure.CommandHandler;
    using Leagues.League;
    using Leagues.League.commandDefinition;
    
    
    /// <summary>
    /// Set the email address for the league
    /// </summary>
    public partial interface ISet_Email_Address_Handler : ICommandHandler<ISet_Email_Address_Definition>
    {
    }
}
