//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using CQRSAzure.CommandHandler;
using CQRSAzure.EventSourcing;
using Leagues.League.commandDefinition;

namespace Leagues.League.commandHandler
{
    
    /// <summary>
    /// Set the email address for the league
    /// </summary>
    [DomainNameAttribute("Leagues")]
    [Category("Organisation")]
    public partial class Set_Email_Address_Handler : 
        CommandHandlerBase<ISet_Email_Address_Definition>, 
        ISet_Email_Address_Handler
    {
        
        /// <summary>
        /// Handle the command definition
        /// Set the email address for the league
        /// </summary>
        /// <param name="cmdToHandle">
        /// The instance of the command definition to handle
        /// </param>
        public override void HandleCommand(ISet_Email_Address_Definition cmdToHandle)
        {
            // TODO : Process the command definition passed in
        }
    }
}
