//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

/// <remarks>
/// Each league will have an unique name
/// </remarks>
namespace Leagues.League.queryDefinition
{
    using CQRSAzure.QueryDefinition;


    public partial interface IGet_League_Summary_Return
    {
        
        /// <summary>
        /// Where the league is currently located
        /// </summary>
        string Location
        {
            get;
        }
        
        /// <summary>
        /// The twitter handle used by the league organisation
        /// </summary>
        string Twitter_Handle
        {
            get;
        }
        
        /// <summary>
        /// The date this league was set up
        /// </summary>
        System.DateTime Date_Incorporated
        {
            get;
        }
    }
    
    public partial interface IGet_League_Summary_Definition : 
        IQueryDefinition<IGet_League_Summary_Return>
    {
        
        /// <summary>
        /// The league for which we want to get the summary information
        /// </summary>
        string League_Name
        {
            get;
        }
    }
}
