//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using CQRSAzure.CommandDefinition;

/// <remarks>
/// Each league will have an unique name
/// </remarks>
namespace Leagues.League.commandDefinition
{
    
    /// <summary>
    /// Create a new running league to which teams can belong
    /// </summary>
    public interface ICreate_New_League_Definition 
        : ICommandDefinition
    {
        
        /// <summary>
        /// The proposed name of the new league
        /// </summary>
        /// <remarks>
        /// The name must be unique or the command should be rejected
        /// </remarks>
        string LeagueName
        {
            get;
        }
        
        /// <summary>
        /// The date the league was created
        /// </summary>
        /// <remarks>
        /// This may be before the event date for leagues that are on-boarded
        /// </remarks>
        System.DateTime Date_Incorporated
        {
            get;
        }
        
        /// <summary>
        /// Where the league is domiciled
        /// </summary>
        string Location
        {
            get;
        }
        
        /// <summary>
        /// The twitter handle of the league organisation
        /// </summary>
        string Twitter_Handle
        {
            get;
        }
        
        /// <summary>
        /// The primary contact address for the league
        /// </summary>
        string Email_Address
        {
            get;
        }
    }
}
