//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using CQRSAzure.CommandDefinition;

/// <remarks>
/// Each league will have an unique name
/// </remarks>
namespace Leagues.League.commandDefinition
{
    


    /// <summary>
    /// Set the email address for the league
    /// </summary>
    [CQRSAzure.EventSourcing.DomainNameAttribute("Leagues")]
    [CQRSAzure.EventSourcing.Category("Organisation")]
    public  class Set_Email_Address_Definition : 
        CommandDefinitionBase, ISet_Email_Address_Definition
    {
        
        /// <summary>
        /// The unique name of this command
        /// Set Email Address
        /// </summary>
        public override string CommandName
        {
            get
            {
                return "Set Email Address";
            }
        }
        
        /// <summary>
        /// The new enail address for the league
        /// </summary>
        public string New_Email_Address
        {
            get
            {
                return base.GetParameterValue<string>("New Email Address", 0);
            }
            set
            {
                base.SetParameterValue("New Email Address", 0, ref value);
            }
        }
        
        public int Notes
        {
            get
            {
                return base.GetParameterValue<int>("Notes", 0);
            }
            set
            {
                base.SetParameterValue("Notes", 0, ref value);
            }
        }
        
        /// <summary>
        /// The name of the league whose email address is being set
        /// </summary>
        /// <remarks>
        /// This is the unique key for the league aggregate
        /// </remarks>
        [CQRSAzure.EventSourcing.AggregateKey()]
        public string LeagueName
        {
            get
            {
                return base.GetParameterValue<string>("LeagueName", 0);
            }
            set
            {
                base.SetParameterValue("LeagueName", 0, ref value);
            }
        }
    }
}
