//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Leagues.League.classifier
{
    using System;
    using CQRSAzure.IdentifierGroup;
    using CQRSAzure.EventSourcing;
    using Leagues.League;
    using Leagues.League.eventDefinition;
    using Leagues.League.projection;
    
    
    /// <summary>
    /// Determine if the league has a twitter handle
    /// </summary>
    [CQRSAzure.EventSourcing.DomainNameAttribute("Leagues")]
    [CQRSAzure.EventSourcing.Category("Social Media")]
    public partial class Has_Twitter_Handle : object, IHas_Twitter_Handle
    {
        
        /// <summary>
        /// Empty constructor for serialisation
        /// This should be removed if serialisation is not needed
        /// </summary>
        public Has_Twitter_Handle()
        {
        }
        
        /// <summary>
        /// The contact details for the league have changed
        /// </summary>
        public IClassifierDataSourceHandler.EvaluationResult EvaluateEvent(IContact_Details_Changed eventToEvaluate)
        {
            // On Contact Details Changed, if Twitter Handle IsEmpty Any set to Include, otherwise set to Exclude
            if (string.IsNullOrWhiteSpace("Any"))
            {
                return IClassifierDataSourceHandler.EvaluationResult.Include;
            }
            else
            {
                return IClassifierDataSourceHandler.EvaluationResult.Exclude;
            }
        }
    }
}
