//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Leagues.League.classifier
{
    using System;
    using CQRSAzure.IdentifierGroup;
    using CQRSAzure.EventSourcing;
    using Leagues.League;
    using Leagues.League.eventDefinition;
    
    
    /// <summary>
    /// Determine if the league has a twitter handle
    /// </summary>
    public partial interface IHas_Twitter_Handle : CQRSAzure.IdentifierGroup.IClassifierEventHandler<IContact_Details_Changed>
    {
    }
}
