//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

/// <remarks>
/// Each league will have an unique name
/// </remarks>
namespace Leagues.League.queryHandler
{
    using CQRSAzure.EventSourcing;
    using CQRSAzure.QueryDefinition;
    using CQRSAzure.QueryHandler;
    using System.Collections.Generic;
    using Leagues.League;
    using Leagues.League.queryDefinition;
    
    
    public partial interface IGet_League_Summary_Handler : 
        IQueryHandler<IGet_League_Summary_Definition, IGet_League_Summary_Return>
    {
        

    }
}
