//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Collections.Generic;
using System.Runtime.Serialization;

/// <remarks>
/// Each league will have an unique name
/// </remarks>
namespace Leagues.League.eventDefinition
{

    /// <summary>
    /// The contact details for the league have changed
    /// </summary>
    public partial class Contact_Details_ChangedSerializer :
        CQRSAzure.EventSourcing.EventSerializer<Contact_Details_Changed>
    {
        
        protected Contact_Details_ChangedSerializer(System.Func<IFormatter> getStreamFormatter, System.Func<Contact_Details_Changed, IDictionary<string, object>> saveNameValuePairsFunction, System.Func<IDictionary<string, object>, Contact_Details_Changed> readNameValuePairsFunction) : 
                base(getStreamFormatter, saveNameValuePairsFunction, readNameValuePairsFunction)
        {
        }
        
        public static Contact_Details_ChangedSerializer Create(System.Func<IFormatter> getStreamFormatter, System.Func<Contact_Details_Changed, IDictionary<string, object>> saveNameValuePairsFunction, System.Func<IDictionary<string, object>, Contact_Details_Changed> readNameValuePairsFunction)
        {
            return new Contact_Details_ChangedSerializer(getStreamFormatter, saveNameValuePairsFunction, readNameValuePairsFunction);
        }
        
        public static IDictionary<string, object> SaveNameValuePairsFunction(Contact_Details_Changed Contact_Details_ChangedEvent)
        {
            Dictionary<string, object> ret = new Dictionary<string, object>();
            ret.Add("Effective From", Contact_Details_ChangedEvent.Effective_From);
            ret.Add("Twitter Handle", Contact_Details_ChangedEvent.Twitter_Handle);
            ret.Add("Email Address", Contact_Details_ChangedEvent.Email_Address);
            return ret;
        }
        
        public static Contact_Details_Changed ReadNameValuePairsFunction(IDictionary<string, object> properties)
        {
            System.DateTime Effective_From_In;
            string Twitter_Handle_In;
            string Email_Address_In;
            Effective_From_In = ((System.DateTime)(properties["Effective From"]));
            Twitter_Handle_In = ((string)(properties["Twitter Handle"]));
            Email_Address_In = ((string)(properties["Email Address"]));
            Contact_Details_Changed ret = new Contact_Details_Changed(Effective_From_In, Twitter_Handle_In, Email_Address_In);
            return ret;
        }
    }
}
