//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using CQRSAzure.EventSourcing;
using Leagues.League;

/// <remarks>
/// Each league will have an unique name
/// </remarks>
namespace Leagues.League.eventDefinition
{


    /// <summary>
    /// The contact details for the league have changed
    /// </summary>
    public partial interface IContact_Details_Changed : 
        IEvent<ILeague>
    {
        
        System.DateTime Effective_From
        {
            get;
        }
        
        /// <summary>
        /// The twitter handle of the league organisation
        /// </summary>
        string Twitter_Handle
        {
            get;
        }
        
        /// <summary>
        /// The primary email address of the league
        /// </summary>
        string Email_Address
        {
            get;
        }
    }
}
