//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using CQRSAzure.EventSourcing;

/// <remarks>
/// Each league will have an unique name
/// </remarks>
namespace Leagues.League.eventDefinition
{

    /// <summary>
    /// A new league was formed
    /// </summary>
    public partial interface IFormed : IEvent<ILeague>
    {
        
        /// <summary>
        /// The date the new league was officially formed
        /// </summary>
        System.DateTime Date_Incorporated
        {
            get;
        }
        
        string Location
        {
            get;
        }
        
        /// <summary>
        /// General notes
        /// </summary>
        /// <remarks>
        /// These are just for logging as no business logic should be stored as notes
        /// </remarks>
        string Notes
        {
            get;
        }
    }
}
