//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Leagues.League
{
    using System;
    using CQRSAzure.EventSourcing;
    
    
    /// <summary>
    /// A league to which clubs may belong
    /// </summary>
    /// <remarks>
    /// Each league will have an unique name
    /// </remarks>
    public partial interface ILeague : CQRSAzure.EventSourcing.IAggregationIdentifier<string>
    {
    }
}
