//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

/// <remarks>
/// This is usally identified by a year or year range, e.g. 2017 or 2017-18
/// </remarks>
namespace Leagues.Season
{
    using System;
    using CQRSAzure.EventSourcing;
    
    
    /// <summary>
    /// A defined season
    /// </summary>
    /// <remarks>
    /// This is usally identified by a year or year range, e.g. 2017 or 2017-18
    /// </remarks>
    [CQRSAzure.EventSourcing.DomainNameAttribute("Leagues")]
    public partial class Season : object, ISeason
    {
        
        private string _Key;
        
        /// <summary>
        /// Empty constructor for serialisation
        /// This should be removed if serialisation is not needed
        /// </summary>
        public Season()
        {
        }
        
        /// <summary>
        /// Create an instance of the aggregate from its key identifier
        /// </summary>
        public Season(string Key_In)
        {
            _Key = Key_In;
        }
        
        /// <summary>
        /// Returns the unique identifier of this Season
        /// </summary>
        public string GetAggregateIdentifier()
        {
            return _Key;
        }
        
        /// <summary>
        /// Returns the unique identifier of this Season
        /// </summary>
        public string GetKey()
        {
            return _Key;
        }
        
        /// <summary>
        /// Sets the unique identifier of this Season
        /// </summary>
        public void SetKey(string Key_In)
        {
            _Key = Key_In;
        }
    }
}
